(()=>{'use strict';
const DL=window.SWBattleCatsDataLoaderV082;
const Marks=window.SWBattleCatsMarksV054;
const RELEASE={version:'V082',note:'KR 15.5.0 캐릭터 성장·레벨 상한 및 초기 레벨업 XP 전수 연결'};
const FILES={cat_form:'cats',enemy:'enemies',stage:'stages'};
const state={index:[],mode:'cat_form',query:'',cache:new Map(),current:null,history:[],strategy:null,hierarchy:null,special:null,progression:null,platforms:null,platform:'mobile',visualCoverage:null,stageVisuals:new Map(),stageBackgroundEffects:new Map(),enemyBaseRegistry:new Map(),deckMode:'progress',stageCtx:null,specialCtx:null};
const $=s=>document.querySelector(s),catalog=$('#catalogView'),detail=$('#detailView'),content=$('#contentView'),search=$('#searchInput');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const {spans}=window.SWBattleCatsLayoutV030,IR=window.SWBattleCatsImageResolverV038,Deck=window.SWBattleCatsDeckEngineV036,Roster=window.SWBattleCatsRosterV035;
const MODE_LABEL={special:'특수',cat_form:'캐릭터 도감',enemy:'적 도감',stage:'스테이지'};
const LIMIT=300;
let storyDetailMap=new Map(),stageNodeMap=new Map();
function syncReleaseUi(){document.title=`SW BATTLE CATS 백과 ${RELEASE.version}`;const local=$('#releaseVersion');if(local)local.textContent=RELEASE.version;const note=$('#releaseNote');if(note)note.textContent=RELEASE.note;let embedded=false;try{embedded=window.self!==window.top}catch(_){embedded=true}if(embedded)document.documentElement.classList.add('swbc-embedded');}
function buildSpecialDisplayItems(payload){if(Array.isArray(payload?.display_entries))return payload.display_entries;const raw=payload?.entries||[];return raw.filter(x=>x?.display_policy?.visible!==false);}
function fitHeroImages(root=document){root.querySelectorAll('img.hero-img').forEach(img=>{const apply=()=>{if(!img.naturalWidth||!img.naturalHeight)return;const maxW=180,maxH=140;const ratio=Math.min(1,maxW/img.naturalWidth,maxH/img.naturalHeight);img.style.width=Math.max(1,Math.round(img.naturalWidth*ratio))+'px';img.style.height=Math.max(1,Math.round(img.naturalHeight*ratio))+'px';img.dataset.nativeSize=`${img.naturalWidth}x${img.naturalHeight}`};if(img.complete)apply();else img.addEventListener('load',apply,{once:true})})}
function setTitle(t,sub=''){ $('#viewTitle').textContent=t; $('#viewSubtitle').textContent=sub||''; }
function countText(total,shown=total){$('#resultCount').textContent=shown<total?`${total.toLocaleString()}개 중 ${shown.toLocaleString()}개 표시`:`${total.toLocaleString()}개`;}
function placeholder(cls){return `<div class="${cls} image-pending">이미지<br>준비 중</div>`}
function imageBox(id,name,cls){const hit=IR.resolve(id);if(!hit)return placeholder(cls);return `<img class="${cls}" src="${esc(hit.src)}" alt="${esc(name)}" loading="lazy" referrerpolicy="no-referrer" data-image-entry="${esc(id)}">`}
function itemImageBox(itemId,name,cls){const hit=IR.resolveItem(itemId);if(!hit)return '';return `<img class="${cls}" src="${esc(hit.src)}" alt="${esc(name)}" loading="lazy" data-item-image="${itemId}">`}
function platformBadges(list){const a=Array.isArray(list)&&list.length?list:['M'];return `<span class="platform-badges">${a.map(p=>`<span class="platform-badge platform-${String(p).toLowerCase()}" title="${p==='M'?'모바일':'Nintendo'}">${esc(p)}</span>`).join('')}</span>`}
function bindImageFallback(root=document){root.querySelectorAll('img[data-image-entry]').forEach(img=>{img.addEventListener('error',()=>{const d=document.createElement('div');d.className=img.className+' image-pending';d.innerHTML='이미지<br>준비 중';img.replaceWith(d)},{once:true})})}
async function loadCategory(cat){if(state.cache.has(cat))return state.cache.get(cat);const d=await DL.load(FILES[cat]),m=new Map(d.entries.map(e=>[e.entry_id,e]));state.cache.set(cat,m);return m}
async function boot(){
 syncReleaseUi();
 const [idx,strat,sstory,hier,smeta,sitems,scombos,sgacha,rankRewards,prog,platforms,visual,visualAssets,stageVisualAssets,stageBackgroundEffects,enemyBaseRegistry]=await Promise.all([
  'index','strategy','strategyStory','hierarchy','specialMeta','specialItems','specialCombos','specialGacha','rankRewards','progression','platforms','visualCoverage','visualAssets','stageVisualAssets','stageBackgroundEffects','enemyBaseRegistry'
 ].map(k=>DL.load(k)));
 state.index=idx.entries.filter(x=>x.category==='cat_form'||x.category==='enemy');state.strategy=strat;Object.assign(state.strategy.stages,sstory.stages||{});Deck.init(state.strategy);state.hierarchy=hier;
 state.special={...smeta,items:sitems.entries||[],display_items:buildSpecialDisplayItems(sitems),combos:scombos.entries||[],gacha_series:sgacha.entries||[],rank_rewards:rankRewards.entries||[]};
 state.special.unit_gacha_index={};for(const g of state.special.gacha_series)for(const u of g.members||[])(state.special.unit_gacha_index[String(u.unit_id)]??=[]).push({series_id:g.series_id,name_ko:g.name_ko,name_status:g.name_status});
 state.progression=prog;state.platforms=platforms;state.visualCoverage=visual;state.stageVisuals=new Map((stageVisualAssets.entries||[]).map(x=>[x.entry_id,x]));state.stageBackgroundEffects=new Map((stageBackgroundEffects.entries||[]).map(x=>[String(x.background_id),x]));state.enemyBaseRegistry=new Map((enemyBaseRegistry.entries||[]).map(x=>[String(x.enemy_base_id),x]));IR.init(visualAssets);storyDetailMap=new Map((hier.story_stage_details||[]).map(e=>[e.entry_id,e]));stageNodeMap=new Map((hier.stage_search_index||[]).map(n=>[n.entry_id,n]));
 bindPlatformButtons();showPlatform(platforms.default_platform||'mobile',false);showMode('cat_form',false);
}
function currentPlatform(){return (state.platforms?.platforms||[]).find(x=>x.id===state.platform)||null}
function platformModeAvailable(p=currentPlatform(),mode=state.mode){if(!p)return false;const c=p.category_availability;if(c&&Object.prototype.hasOwnProperty.call(c,mode))return !!c[mode];return !!p.available}
function activePlatform(){document.querySelectorAll('[data-platform]').forEach(b=>b.classList.toggle('active',b.dataset.platform===state.platform));const p=currentPlatform();const dv=document.querySelector('#platformDataVersion');if(dv)dv.textContent=platformModeAvailable(p)?(p.data_version||''):'자료 미확보'}
function bindPlatformButtons(){document.querySelectorAll('[data-platform]').forEach(b=>b.addEventListener('click',()=>showPlatform(b.dataset.platform)))}
function refreshSearchGate(){const p=currentPlatform(),ok=platformModeAvailable(p);search.disabled=!ok;if(!ok)search.placeholder=`${p?.name_ko||'해당'}판 ${MODE_LABEL[state.mode]||'자료'} 정리 중`;else activeNav()}
function showPlatform(id,rerender=true){state.platform=id;state.query='';search.value='';state.current=null;state.history=[];state.stageCtx=null;state.specialCtx=null;activePlatform();refreshSearchGate();if(rerender)renderCurrent()}
function renderPlatformUnavailable(){const p=currentPlatform();setTitle(`${p?.name_ko||'플랫폼'} · ${MODE_LABEL[state.mode]||''}`,'별도 판본 데이터');countText(0);content.innerHTML=`<div class="platform-unavailable"><h2>${esc(p?.name_ko||'Nintendo')}판 ${esc(MODE_LABEL[state.mode]||'')}</h2><p>${esc(p?.note||'현재 프로젝트에 해당 판본 원본 데이터가 없습니다.')}</p><p>모바일판 데이터를 Nintendo판으로 대신 표시하지 않습니다. 검증된 canonical 데이터가 수입된 범주부터 순차적으로 열립니다.</p></div>`}
function activeNav(){document.querySelectorAll('.bottom-toolbar [data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));search.placeholder=state.mode==='cat_form'?'캐릭터 이름·등급·설명 검색':state.mode==='enemy'?'적 이름 검색':state.mode==='stage'?'스테이지 이름 검색': '아이템·뽑기·냥콤보·유저랭크 검색'}
function showMode(mode,clear=true){state.mode=mode;if(clear){state.query='';search.value=''}state.current=null;state.history=[];state.stageCtx=null;state.specialCtx=null;detail.hidden=true;catalog.hidden=false;refreshSearchGate();renderCurrent();window.scrollTo({top:0,behavior:'auto'})}
function resultCard(x){return `<button class="entry-card" type="button" data-entry="${esc(x.entry_id)}" data-category="${esc(x.category)}">${imageBox(x.entry_id,x.name_ko,'entry-thumb')}<div><b>${esc(x.display_name_ko||x.name_ko)} ${platformBadges(x.platforms_verified)}</b><small>${esc(x.subtitle||'')}</small></div></button>`}
function renderStandardList(){const q=state.query.trim().toLowerCase(),rows=state.index.filter(x=>x.category===state.mode&&(!q||(x.name_ko+' '+x.keywords+' '+x.subtitle).toLowerCase().includes(q)));const shown=rows.slice(0,LIMIT);setTitle(MODE_LABEL[state.mode],state.mode==='cat_form'?'형태별 능력·진화·획득처': '속성·특능·등장 스테이지');countText(rows.length,shown.length);content.innerHTML=shown.length?`<div class="entry-list">${shown.map(resultCard).join('')}</div>`:'<div class="empty">검색 결과가 없습니다.</div>';bindImageFallback(content)}
function seriesCard(s){let sub=s.section;if(s.kind==='chapters')sub+=` · ${s.chapters.length}개 장`;else if(s.kind==='maps')sub+=` · ${s.maps.length}개 맵`;else sub+=` · ${s.stages.length}개 스테이지`;return `<button class="hier-card" type="button" data-stage-series="${esc(s.id)}"><b>${esc(s.name_ko)}</b><small>${esc(sub)}</small></button>`}
function renderStageRoot(){const groups={};for(const s of state.hierarchy.series||[])(groups[s.section]??=[]).push(s);setTitle('스테이지','게임 분류 → 장/맵 → 실제 진행 순서');countText(state.hierarchy.counts.searchable_stages);content.innerHTML=Object.entries(groups).map(([g,arr])=>`<section class="hier-group"><h2>${esc(g)}</h2><div class="hier-grid">${arr.map(seriesCard).join('')}</div></section>`).join('')}
function stageSearch(){const q=state.query.trim().toLowerCase(),rows=(state.hierarchy.stage_search_index||[]).filter(x=>(x.name_ko+' '+x.breadcrumb).toLowerCase().includes(q));const shown=rows.slice(0,LIMIT);setTitle('스테이지 검색',`“${state.query}”`);countText(rows.length,shown.length);content.innerHTML=shown.length?`<div class="stage-search-list">${shown.map(x=>`<button type="button" class="stage-row" data-stage-entry="${esc(x.entry_id)}"><b>${esc(x.name_ko)}</b><small>${esc(x.breadcrumb)}</small></button>`).join('')}</div>`:'<div class="empty">검색 결과가 없습니다.</div>'}
function getSeries(id){return (state.hierarchy.series||[]).find(x=>x.id===id)}
function renderSeries(id){const s=getSeries(id);if(!s)return renderStageRoot();state.stageCtx={type:'series',series:id};setTitle(s.name_ko,s.section);let html=`<button class="inline-back" data-stage-back="root" type="button">← 스테이지 분류</button>`;if(s.kind==='chapters')html+=`<div class="hier-grid">${s.chapters.map(ch=>`<button class="hier-card" data-stage-chapter="${esc(ch.id)}" data-series="${esc(id)}"><b>${esc(ch.name_ko)}</b><small>${ch.stages.length}개 스테이지</small></button>`).join('')}</div>`;else if(s.kind==='maps')html+=`<div class="map-list">${s.maps.map(m=>`<button class="map-row" data-stage-map="${esc(m.id)}" data-series="${esc(id)}"><b>${esc(m.name_ko)}</b><small>${m.stages.length}개 스테이지</small></button>`).join('')}</div>`;else html+=stageRows(s.stages);countText(s.kind==='chapters'?s.chapters.reduce((a,x)=>a+x.stages.length,0):s.kind==='maps'?s.maps.reduce((a,x)=>a+x.stages.length,0):s.stages.length);content.innerHTML=html}
function stageRows(arr){return `<div class="stage-order-list">${arr.map(x=>`<button type="button" class="stage-row" data-stage-entry="${esc(x.entry_id)}"><span class="order">${String(x.play_order||'').padStart(2,'0')}</span><div><b>${esc(x.name_ko)} ${platformBadges(['M'])}</b><small>${esc(x.breadcrumb)}</small></div></button>`).join('')}</div>`}
function renderChapter(seriesId,chId){const s=getSeries(seriesId),ch=s?.chapters?.find(x=>x.id===chId);if(!ch)return renderSeries(seriesId);state.stageCtx={type:'chapter',series:seriesId,id:chId};setTitle(`${s.name_ko} ${ch.name_ko}`,'실제 플레이 순서');countText(ch.stages.length);content.innerHTML=`<button class="inline-back" data-stage-series="${esc(seriesId)}" type="button">← ${esc(s.name_ko)}</button>${stageRows(ch.stages)}`}
function renderMap(seriesId,mapId){const s=getSeries(seriesId),m=s?.maps?.find(x=>x.id===mapId);if(!m)return renderSeries(seriesId);state.stageCtx={type:'map',series:seriesId,id:mapId};setTitle(m.name_ko,s.name_ko);countText(m.stages.length);content.innerHTML=`<button class="inline-back" data-stage-series="${esc(seriesId)}" type="button">← ${esc(s.name_ko)}</button>${stageRows(m.stages)}`}
function renderStage(){if(state.query.trim())return stageSearch();if(!state.stageCtx)return renderStageRoot();if(state.stageCtx.type==='series')return renderSeries(state.stageCtx.series);if(state.stageCtx.type==='chapter')return renderChapter(state.stageCtx.series,state.stageCtx.id);if(state.stageCtx.type==='map')return renderMap(state.stageCtx.series,state.stageCtx.id);renderStageRoot()}
function specialMenuCard(x){return `<button class="special-menu-card" type="button" data-special="${esc(x.id)}"><b>${esc(x.name_ko)}</b><small>${x.id==='items'?'전투 아이템·티켓·재화':x.id==='gacha'?'확인된 뽑기 시리즈와 포함 캐릭터':x.id==='combos'?'필요 캐릭터와 발동 효과':x.id==='materials'?'개다래·수석 등 강화 재료':x.id==='rank'?'유저랭크 달성 보상·레벨 상한 해방':'게임 능력/특성 정보'}</small></button>`}
function renderSpecialRoot(){setTitle('특수','아이템·뽑기·냥콤보 등 게임 정보');countText(state.special.menu.length);content.innerHTML=`<div class="special-menu-grid">${state.special.menu.map(specialMenuCard).join('')}</div>`}
function itemRows(items){return `<div class="simple-list">${items.map(x=>{const icon=itemImageBox(x.item_id,(x.display_name_ko||x.name_ko),'item-thumb');return `<button class="simple-row item-row ${icon?'has-image':'no-image'}" data-special-item="${x.item_id}">${icon}<div><b>${esc(x.display_name_ko||x.name_ko)} ${platformBadges(x.platforms_verified)}</b><small>${esc(x.display_category||x.category)}${x.description_ko?' · '+esc(x.description_ko.slice(0,80)):''}</small></div></button>`}).join('')}</div>`}
function renderSpecialCategory(id){state.specialCtx=id;let html=`<button class="inline-back" data-special-back="1">← 특수</button>`,total=0;if(id==='items'||id==='materials'){let rows=state.special.display_items||[];if(id==='materials')rows=rows.filter(x=>{const c=x.display_category||x.category||'';return c==='진화/강화 재료'||c==='재료'||c.includes('냥코성 개발')});const q=state.query.trim().toLowerCase();if(q)rows=rows.filter(x=>((x.display_name_ko||x.name_ko)+' '+(x.display_category||x.category)+' '+x.description_ko).toLowerCase().includes(q));total=rows.length;setTitle(id==='materials'?'진화 재료':'아이템 / 재화',id==='items'?'전투 아이템·티켓·재화·강화 재료':'개다래·수석 등');html+=itemRows(rows.slice(0,LIMIT))}else if(id==='combos'){let rows=state.special.combos||[],q=state.query.trim().toLowerCase();if(q)rows=rows.filter(x=>(x.name_ko+' '+x.effect_ko+' '+x.required_units.map(u=>u.name_ko).join(' ')).toLowerCase().includes(q));total=rows.length;setTitle('냥콤보','필요 캐릭터와 발동 효과');html+=`<div class="simple-list">${rows.slice(0,LIMIT).map(x=>`<button class="simple-row" data-special-combo="${x.combo_id}"><b>${esc(x.name_ko)}</b><small>${esc(x.effect_ko)} · ${esc(x.required_units.map(u=>u.name_ko).join(' + '))}</small></button>`).join('')}</div>`}else if(id==='gacha'){let rows=state.special.gacha_series||[],q=state.query.trim().toLowerCase();if(q)rows=rows.filter(x=>(x.name_ko+' '+x.members.map(u=>u.name_ko).join(' ')).toLowerCase().includes(q));total=rows.length;setTitle('뽑기','확인된 시리즈와 포함 캐릭터');html+=`<div class="simple-list">${rows.slice(0,LIMIT).map(x=>`<button class="simple-row" data-special-gacha-series="${x.series_id}"><b>${esc(x.name_ko)}</b><small>확인 캐릭터 ${x.member_count}명</small></button>`).join('')}</div><div class="source-note">${esc(state.special.gacha_note)}</div>`}else if(id==='rank'){let rows=state.special.rank_rewards||[],q=state.query.trim().toLowerCase();if(q)rows=rows.filter(x=>(String(x.rank)+' '+x.message_ko+' '+x.kind).toLowerCase().includes(q));total=rows.length;setTitle('유저랭크 보상','KR 15.5.0 클라이언트 한국어 달성 보상');html+=`<div class="simple-list">${rows.slice(0,LIMIT).map(x=>`<div class="simple-row"><b>유저랭크 ${x.rank.toLocaleString()}</b><small>${esc(x.message_ko)} · ${esc(x.kind)}</small></div>`).join('')}</div><div class="source-note">한국어 원문이 직접 존재하는 342개 보상만 표시합니다. 원문이 없는 내부 행은 노출하지 않습니다.</div>`}else if(id==='abilities'){setTitle('능력 / 특성','현재 백과 데이터의 대응 능력 기준');const rules=state.strategy.rules||[],seen=new Map();for(const r of rules)if(r.required_trait_key&&!seen.has(r.required_trait_key))seen.set(r.required_trait_key,r.capability_name_ko);const arr=[...seen.entries()].sort((a,b)=>a[1].localeCompare(b[1],'ko'));total=arr.length;html+=`<div class="ability-grid">${arr.map(([k,n])=>`<div class="ability-card ability-card-marked">${markItem(n,'ability')}</div>`).join('')}</div>`}countText(total,Math.min(total,LIMIT));content.innerHTML=html}
function specialSearchAll(){const q=state.query.trim().toLowerCase(),hits=[];for(const x of state.special.display_items||[])if(((x.display_name_ko||x.name_ko)+' '+(x.display_category||x.category)+' '+x.description_ko).toLowerCase().includes(q))hits.push({kind:'item',id:x.item_id,name:(x.display_name_ko||x.name_ko),sub:(x.display_category||x.category||'아이템 / 재화')});for(const x of state.special.combos||[])if((x.name_ko+' '+x.effect_ko).toLowerCase().includes(q))hits.push({kind:'combo',id:x.combo_id,name:x.name_ko,sub:'냥콤보 · '+x.effect_ko});for(const x of state.special.gacha_series||[])if((x.name_ko+' '+x.members.map(u=>u.name_ko).join(' ')).toLowerCase().includes(q))hits.push({kind:'gacha-series',id:x.series_id,name:x.name_ko,sub:`뽑기 · 확인 캐릭터 ${x.member_count}명`});for(const x of state.special.rank_rewards||[])if((String(x.rank)+' '+x.message_ko+' '+x.kind).toLowerCase().includes(q))hits.push({kind:'rank',id:x.rank,name:`유저랭크 ${x.rank.toLocaleString()}`,sub:x.message_ko});setTitle('특수 검색',`“${state.query}”`);countText(hits.length,Math.min(hits.length,LIMIT));content.innerHTML=`<div class="simple-list">${hits.slice(0,LIMIT).map(x=>`<button class="simple-row" data-special-${x.kind}="${x.id}"><b>${esc(x.name)}</b><small>${esc(x.sub)}</small></button>`).join('')}</div>`}
function renderSpecial(){if(state.query.trim()&&!state.specialCtx)return specialSearchAll();if(!state.specialCtx)return renderSpecialRoot();renderSpecialCategory(state.specialCtx)}
function renderCurrent(){catalog.hidden=false;detail.hidden=true;if(!platformModeAvailable())return renderPlatformUnavailable();if(state.mode==='cat_form'||state.mode==='enemy')renderStandardList();else if(state.mode==='stage')renderStage();else renderSpecial();}
function markItem(item,kind='ability'){const hit=kind==='trait'?Marks?.trait(item):Marks?.ability(item);return `<span class="mark-item ${kind}${hit?'':' mark-unmapped'}">${hit?`<img class="mark-icon" src="${esc(hit.src)}" alt="" loading="lazy">`:''}<span class="mark-text">${esc(item)}</span></span>`}
function renderFieldValue(e,f){const label=String(f.label||''),value=String(f.value??'');if(!Marks)return esc(value);if(label==='공격 대상'||label==='속성'){const items=Marks.splitTraits(value);return items.length?`<div class="mark-list mark-traits">${items.map(x=>markItem(x,'trait')).join('')}</div>`:esc(value)}if(label==='특성'||label==='특수 능력'){const items=Marks.splitAbilityLines(value);return items.length?`<div class="mark-list mark-abilities">${items.map(x=>markItem(x,'ability')).join('')}</div>`:esc(value)}if(label==='유효 대응 특성'){const items=Marks.splitResponses(value);return items.length?`<div class="mark-list mark-responses">${items.map(x=>markItem(x,'ability')).join('')}</div>`:esc(value)}return esc(value)}
function standardSections(e){return (e.sections||[]).map(g=>{const sm=spans(g.fields||[]);return `<section class="info-group"><h2 class="info-group-title">${esc(g.title)}</h2><div class="info-grid">${(g.fields||[]).map((f,i)=>{const sp=sm[i]||6,links=(f.links||[]).map(l=>`<button class="info-link" type="button" data-open="${esc(l.entry_id)}">${esc(l.label)}</button>`).join('');return `<div class="info-cell span-${sp}"><div class="info-label">${esc(f.label)}</div><div class="info-value">${renderFieldValue(e,f)}${links?`<div class="info-links">${links}</div>`:''}</div></div>`}).join('')}</div></section>`}).join('')}
function catGachaHtml(e){if(e.category!=='cat_form')return'';const uid=String(e.classification.unit_id),all=state.special.unit_gacha_index?.[uid]||[],named=[];for(const x of all){if(x.name_status!=='KOREAN_SERIES_LABEL_CROSSCHECKED')continue;if(!named.some(y=>y.series_id===x.series_id))named.push(x)}if(!named.length)return'';return `<section class="info-group"><h2 class="info-group-title">포함 뽑기</h2><div class="info-cell span-6"><div class="info-label">확인된 시리즈</div><div class="info-value"><div class="info-links">${named.map(x=>`<button class="info-link" data-special-gacha-series="${x.series_id}">${esc(x.name_ko)}</button>`).join('')}</div></div></div></section>`}
function rosterControl(e){if(e.category!=='cat_form')return'';const u=e.classification.unit_id,f=e.classification.form_no,owned=Roster.isOwned(u,f);return `<div class="hero-actions"><button class="roster-btn ${owned?'owned':''}" type="button" data-roster-unit="${u}" data-roster-form="${f}">${owned?'보유 등록됨 · 해제':'이 형태까지 보유 등록'}</button></div>`}
function nodeFor(e){return stageNodeMap.get(e.entry_id)||null}
function deckPanel(e){if(e.category!=='stage')return'';const node=nodeFor(e),sid=e.classification.stage_native_id||node?.battle_stage_native_id,series=node?.series_id||e.classification.series_code,ch=node?.chapter_no||e.classification.chapter_no;let owned=null,allowed=null,note='',mode=state.deckMode;if(mode==='owned')owned=Roster.read();if(mode==='progress'){const key=series==='EOC'&&ch?`EOC:CH${ch}`:null,pol=key?state.progression.policies?.[key]:null;if(pol){allowed=pol.allowed_entry_ids;note=pol.note}else{mode='all';note=state.progression.fallback.note}}
 const d=Deck.recommend(sid,{owned,allowedEntries:allowed});const cards=d.slots.map(x=>`<button class="deck-card" type="button" data-open="${esc(x.entry_id)}">${imageBox(x.entry_id,x.name_ko,'deck-thumb')}<div class="deck-slot">#${x.slot} · ${esc(x.role_ko)}</div><b>${esc(x.name_ko)}</b><small>비용 ${esc(x.stats.cost)} · 사거리 ${esc(x.stats.range)}</small><p>${esc(x.reasons.slice(0,2).join(' / '))}</p></button>`).join('');const shortage=d.slots.length<10?`<div class="deck-warning">현재 선택 기준에서는 추천 가능한 서로 다른 캐릭터가 ${d.slots.length}종입니다. 없는 강캐를 억지로 채우지 않습니다.</div>`:'';return `<section class="deck-panel"><div class="deck-head"><div><h2>추천 편성</h2><p>공식 공략 공식이 아닌 KR15.5 데이터 기반 추천입니다.</p></div><div class="deck-mode"><button data-deck-mode="progress" class="${state.deckMode==='progress'?'active':''}">진행 기준</button><button data-deck-mode="owned" class="${state.deckMode==='owned'?'active':''}">보유만 (${Roster.count()})</button><button data-deck-mode="all" class="${state.deckMode==='all'?'active':''}">전체 참고</button></div></div>${note?`<div class="deck-note">${esc(note)}</div>`:''}${shortage}<div class="deck-grid">${cards}</div></section>`}
function stageVisualHtml(e){if(e.category!=='stage')return'';const v=state.stageVisuals.get(e.entry_id);if(!v||v.verification_status!=='VERIFIED')return'';const bg=v.background_path?`<img class="stage-bg-img" src="${esc(v.background_path)}" alt="${esc(e.names?.ko||'스테이지')} 배경" loading="lazy">`:'';const base=v.enemy_base_path?`<img class="stage-base-img" src="${esc(v.enemy_base_path)}" alt="${esc(e.names?.ko||'스테이지')} 적 성" loading="lazy">`:'';if(!bg&&!base)return'';return `<div class="stage-visual-panel">${bg?`<div class="stage-visual-item"><div class="stage-visual-label">배경</div>${bg}</div>`:''}${base?`<div class="stage-visual-item"><div class="stage-visual-label">적 성</div>${base}</div>`:''}</div>`}
function detailHtml(e){const node=nodeFor(e),crumb=node?.breadcrumb||e.classification?.hierarchy_breadcrumb||'',displayName=node?.name_ko||e.names.ko;const noImage=e.category==='stage';const hero=`${crumb?`<div class="breadcrumb">${esc(crumb)}</div>`:''}<div class="detail-hero${noImage?' no-image':''}">${noImage?'':`<div class="hero-image">${imageBox(e.entry_id,displayName,'hero-img')}</div>`}<div class="hero-copy"><h1>${esc(displayName)} ${platformBadges(e.source_meta?.platforms_verified||['M'])}</h1>${e.names.ja?`<div class="ja">${esc(e.names.ja)}</div>`:''}<div class="type">${esc(e.ui_category)}</div>${rosterControl(e)}</div></div>`;const rel=(e.relations||[]).length?`<div class="relation-row">${e.relations.map(r=>`<button data-open="${esc(r.entry_id)}">${esc(r.label)}</button>`).join('')}</div>`:'';return `<button class="detail-back" type="button" data-detail-back="1">← 이전</button>`+hero+stageVisualHtml(e)+`<div class="detail-sections">${standardSections(e)}${catGachaHtml(e)}</div>`+deckPanel(e)+rel}
function catFromId(id){if(id.startsWith('cat:'))return'cat_form';if(id.startsWith('enemy:'))return'enemy';return'stage'}
async function getEntry(id,cat){if(storyDetailMap.has(id))return storyDetailMap.get(id);const map=await loadCategory(cat);return map.get(id)||null}
async function openEntry(id,cat,push=true){const e=await getEntry(id,cat);if(!e)return;if(push&&state.current)state.history.push(state.current);state.current={id,cat};catalog.hidden=true;detail.hidden=false;detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail);fitHeroImages(detail);window.scrollTo({top:0,behavior:'auto'})}
function bindDetail(e){detail.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openEntry(b.dataset.open,catFromId(b.dataset.open))));const rb=detail.querySelector('[data-roster-unit]');if(rb)rb.addEventListener('click',()=>{const u=+rb.dataset.rosterUnit,f=+rb.dataset.rosterForm;if(Roster.isOwned(u,f))Roster.remove(u);else Roster.setOwned(u,f);detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail);fitHeroImages(detail)});detail.querySelectorAll('[data-deck-mode]').forEach(b=>b.addEventListener('click',()=>{state.deckMode=b.dataset.deckMode;detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail);fitHeroImages(detail)}));const back=detail.querySelector('[data-detail-back]');if(back)back.addEventListener('click',goBack);detail.querySelectorAll('[data-special-gacha-series]').forEach(b=>b.addEventListener('click',()=>openSpecialGachaSeries(+b.dataset.specialGachaSeries)))}
function goBack(){if(state.history.length){const p=state.history.pop();openEntry(p.id,p.cat,false)}else{state.current=null;detail.hidden=true;catalog.hidden=false;renderCurrent()}}
function openSpecialItem(id){const x=(state.special.display_items||[]).find(x=>x.item_id===id)||(state.special.items||[]).find(x=>x.item_id===id);if(!x)return;state.current={special:'item',id};catalog.hidden=true;detail.hidden=false;const icon=itemImageBox(x.item_id,x.name_ko,'special-item-icon');detail.innerHTML=`<button class="detail-back" data-detail-special-back>← 이전</button><div class="special-detail">${icon}<h1>${esc(x.display_name_ko||x.name_ko)} ${platformBadges(x.platforms_verified)}</h1><div class="tag">${esc(x.display_category||x.category)}</div><p>${esc(x.description_ko||'클라이언트 설명 없음')}</p><small>KR 15.5.0${icon?' · 실제 아이콘 연결':''}${x.duplicate_raw_rows>1?` · 내부 중복 ${x.duplicate_raw_rows}행 통합`:''}</small></div>`;detail.querySelector('[data-detail-special-back]').onclick=()=>{detail.hidden=true;catalog.hidden=false;renderCurrent()}}
function openSpecialCombo(id){const x=(state.special.combos||[]).find(x=>x.combo_id===id);if(!x)return;catalog.hidden=true;detail.hidden=false;detail.innerHTML=`<button class="detail-back" data-detail-special-back>← 이전</button><div class="special-detail"><h1>${esc(x.name_ko)}</h1><h2>${esc(x.effect_ko)}</h2><div class="member-grid">${x.required_units.map(u=>`<button data-open="${esc(u.entry_id)}">${imageBox(u.entry_id,u.name_ko,'member-thumb')}<b>${esc(u.name_ko)}</b></button>`).join('')}</div></div>`;detail.querySelector('[data-detail-special-back]').onclick=()=>{detail.hidden=true;catalog.hidden=false;renderCurrent()};detail.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEntry(b.dataset.open,'cat_form'));bindImageFallback(detail)}
function openSpecialGachaSeries(id){const x=(state.special.gacha_series||[]).find(x=>x.series_id===id);if(!x)return;state.mode='special';activeNav();catalog.hidden=true;detail.hidden=false;detail.innerHTML=`<button class="detail-back" data-detail-special-back>← 이전</button><div class="special-detail"><h1>${esc(x.name_ko)}</h1><p>${esc(x.note||'KR 15.5.0 클라이언트 구성 기준')}</p><div class="member-grid">${x.members.map(u=>`<button data-open="${esc(u.entry_id)}">${imageBox(u.entry_id,u.name_ko,'member-thumb')}<b>${esc(u.name_ko)}</b></button>`).join('')}</div><small>확인 캐릭터 ${x.member_count}명</small></div>`;detail.querySelector('[data-detail-special-back]').onclick=()=>{detail.hidden=true;catalog.hidden=false;renderSpecialCategory('gacha')};detail.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEntry(b.dataset.open,'cat_form'));bindImageFallback(detail)}
content.addEventListener('click',e=>{let b=e.target.closest('[data-entry]');if(b)return openEntry(b.dataset.entry,b.dataset.category);b=e.target.closest('[data-stage-entry]');if(b)return openEntry(b.dataset.stageEntry,'stage');b=e.target.closest('[data-stage-series]');if(b)return renderSeries(b.dataset.stageSeries);b=e.target.closest('[data-stage-chapter]');if(b)return renderChapter(b.dataset.series,b.dataset.stageChapter);b=e.target.closest('[data-stage-map]');if(b)return renderMap(b.dataset.series,b.dataset.stageMap);b=e.target.closest('[data-stage-back]');if(b){state.stageCtx=null;return renderStageRoot()}b=e.target.closest('[data-special]');if(b)return renderSpecialCategory(b.dataset.special);b=e.target.closest('[data-special-back]');if(b){state.specialCtx=null;return renderSpecialRoot()}b=e.target.closest('[data-special-item]');if(b)return openSpecialItem(+b.dataset.specialItem);b=e.target.closest('[data-special-combo]');if(b)return openSpecialCombo(+b.dataset.specialCombo);b=e.target.closest('[data-special-gacha-series]');if(b)return openSpecialGachaSeries(+b.dataset.specialGachaSeries);b=e.target.closest('[data-special-rank]');if(b){state.specialCtx='rank';state.query=String(b.dataset.specialRank);search.value=state.query;return renderSpecialCategory('rank')}});
search.addEventListener('input',e=>{state.query=e.target.value;if(state.current){state.current=null;detail.hidden=true;catalog.hidden=false}renderCurrent()});
document.querySelectorAll('.bottom-toolbar [data-mode]').forEach(b=>b.addEventListener('click',()=>showMode(b.dataset.mode)));
const home=document.querySelector('[data-action="home"]');if(home)home.addEventListener('click',()=>showMode('cat_form'));
window.addEventListener('swbattlecats:roster-changed',()=>{if(state.current?.cat==='stage'){getEntry(state.current.id,'stage').then(e=>{detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail);fitHeroImages(detail)})}});
boot().catch(err=>{content.innerHTML='<div class="empty">데이터를 불러오지 못했습니다.<br>배포 파일 구성을 확인해 주세요.</div>';console.error(err)});
window.SWBattleCatsEncyclopediaV082={showMode,openEntry,showPlatform};
})();
