(()=>{'use strict';
const DATA_BASE='../data/';
const FILES={cat_form:'encyclopedia-cats-v030.json',enemy:'encyclopedia-enemies-v030.json',stage:'encyclopedia-stages-v030.json'};
const state={index:[],mode:'cat_form',query:'',cache:new Map(),current:null,history:[],strategy:null,hierarchy:null,special:null,progression:null,deckMode:'progress',stageCtx:null,specialCtx:null};
const $=s=>document.querySelector(s),catalog=$('#catalogView'),detail=$('#detailView'),content=$('#contentView'),search=$('#searchInput');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const {spans}=window.SWBattleCatsLayoutV030,IR=window.SWBattleCatsImageResolverV036,Deck=window.SWBattleCatsDeckEngineV036,Roster=window.SWBattleCatsRosterV035;
const MODE_LABEL={special:'특수',cat_form:'캐릭터 도감',enemy:'적 도감',stage:'스테이지'};
const LIMIT=300;
let storyDetailMap=new Map(),stageNodeMap=new Map();
function setTitle(t,sub=''){ $('#viewTitle').textContent=t; $('#viewSubtitle').textContent=sub||''; }
function countText(total,shown=total){$('#resultCount').textContent=shown<total?`${total.toLocaleString()}개 중 ${shown.toLocaleString()}개 표시`:`${total.toLocaleString()}개`;}
function placeholder(cls){return `<div class="${cls} image-pending">이미지<br>준비 중</div>`}
function imageBox(id,name,cls){const hit=IR.resolve(id);if(!hit)return placeholder(cls);return `<img class="${cls}" src="${esc(hit.src)}" alt="${esc(name)}" loading="lazy" referrerpolicy="no-referrer" data-image-entry="${esc(id)}">`}
function bindImageFallback(root=document){root.querySelectorAll('img[data-image-entry]').forEach(img=>{img.addEventListener('error',()=>{const d=document.createElement('div');d.className=img.className+' image-pending';d.innerHTML='이미지<br>준비 중';img.replaceWith(d)},{once:true})})}
async function loadCategory(cat){if(state.cache.has(cat))return state.cache.get(cat);const r=await fetch(DATA_BASE+FILES[cat],{cache:'no-store'});if(!r.ok)throw new Error(cat+' load failed');const d=await r.json(),m=new Map(d.entries.map(e=>[e.entry_id,e]));state.cache.set(cat,m);return m}
async function boot(){
 await IR.load();
 const urls=['encyclopedia-index-v030.json','strategy-runtime-v034.json','strategy-story-v036.json','stage-hierarchy-v036.json','special-v036.json','progression-v036.json'];
 const rs=await Promise.all(urls.map(x=>fetch(DATA_BASE+x,{cache:'no-store'})));if(rs.some(x=>!x.ok))throw new Error('V036 data load failed');
 const [idx,strat,sstory,hier,special,prog]=await Promise.all(rs.map(x=>x.json()));
 state.index=idx.entries.filter(x=>x.category==='cat_form'||x.category==='enemy');state.strategy=strat;Object.assign(state.strategy.stages,sstory.stages||{});Deck.init(state.strategy);state.hierarchy=hier;state.special=special;state.progression=prog;
 storyDetailMap=new Map((hier.story_stage_details||[]).map(e=>[e.entry_id,e]));stageNodeMap=new Map((hier.stage_search_index||[]).map(n=>[n.entry_id,n]));
 showMode('cat_form',false);
}
function activeNav(){document.querySelectorAll('.bottom-toolbar [data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));search.placeholder=state.mode==='cat_form'?'캐릭터 이름 검색':state.mode==='enemy'?'적 이름 검색':state.mode==='stage'?'스테이지 이름 검색': '아이템·뽑기·냥콤보 검색'}
function showMode(mode,clear=true){state.mode=mode;if(clear){state.query='';search.value=''}state.current=null;state.history=[];state.stageCtx=null;state.specialCtx=null;detail.hidden=true;catalog.hidden=false;activeNav();renderCurrent();window.scrollTo({top:0,behavior:'auto'})}
function resultCard(x){return `<button class="entry-card" type="button" data-entry="${esc(x.entry_id)}" data-category="${esc(x.category)}">${imageBox(x.entry_id,x.name_ko,'entry-thumb')}<div><b>${esc(x.name_ko)}</b><small>${esc(x.subtitle||'')}</small></div></button>`}
function renderStandardList(){const q=state.query.trim().toLowerCase(),rows=state.index.filter(x=>x.category===state.mode&&(!q||(x.name_ko+' '+x.keywords+' '+x.subtitle).toLowerCase().includes(q)));const shown=rows.slice(0,LIMIT);setTitle(MODE_LABEL[state.mode],state.mode==='cat_form'?'형태별 능력·진화·획득처': '속성·특능·등장 스테이지');countText(rows.length,shown.length);content.innerHTML=shown.length?`<div class="entry-list">${shown.map(resultCard).join('')}</div>`:'<div class="empty">검색 결과가 없습니다.</div>';bindImageFallback(content)}
function seriesCard(s){let sub=s.section;if(s.kind==='chapters')sub+=` · ${s.chapters.length}개 장`;else if(s.kind==='maps')sub+=` · ${s.maps.length}개 맵`;else sub+=` · ${s.stages.length}개 스테이지`;return `<button class="hier-card" type="button" data-stage-series="${esc(s.id)}"><b>${esc(s.name_ko)}</b><small>${esc(sub)}</small></button>`}
function renderStageRoot(){const groups={};for(const s of state.hierarchy.series||[])(groups[s.section]??=[]).push(s);setTitle('스테이지','게임 분류 → 장/맵 → 실제 진행 순서');countText(state.hierarchy.counts.searchable_stages);content.innerHTML=Object.entries(groups).map(([g,arr])=>`<section class="hier-group"><h2>${esc(g)}</h2><div class="hier-grid">${arr.map(seriesCard).join('')}</div></section>`).join('')}
function stageSearch(){const q=state.query.trim().toLowerCase(),rows=(state.hierarchy.stage_search_index||[]).filter(x=>(x.name_ko+' '+x.breadcrumb).toLowerCase().includes(q));const shown=rows.slice(0,LIMIT);setTitle('스테이지 검색',`“${state.query}”`);countText(rows.length,shown.length);content.innerHTML=shown.length?`<div class="stage-search-list">${shown.map(x=>`<button type="button" class="stage-row" data-stage-entry="${esc(x.entry_id)}"><b>${esc(x.name_ko)}</b><small>${esc(x.breadcrumb)}</small></button>`).join('')}</div>`:'<div class="empty">검색 결과가 없습니다.</div>'}
function getSeries(id){return (state.hierarchy.series||[]).find(x=>x.id===id)}
function renderSeries(id){const s=getSeries(id);if(!s)return renderStageRoot();state.stageCtx={type:'series',series:id};setTitle(s.name_ko,s.section);let html=`<button class="inline-back" data-stage-back="root" type="button">← 스테이지 분류</button>`;if(s.kind==='chapters')html+=`<div class="hier-grid">${s.chapters.map(ch=>`<button class="hier-card" data-stage-chapter="${esc(ch.id)}" data-series="${esc(id)}"><b>${esc(ch.name_ko)}</b><small>${ch.stages.length}개 스테이지</small></button>`).join('')}</div>`;else if(s.kind==='maps')html+=`<div class="map-list">${s.maps.map(m=>`<button class="map-row" data-stage-map="${esc(m.id)}" data-series="${esc(id)}"><b>${esc(m.name_ko)}</b><small>${m.stages.length}개 스테이지</small></button>`).join('')}</div>`;else html+=stageRows(s.stages);countText(s.kind==='chapters'?s.chapters.reduce((a,x)=>a+x.stages.length,0):s.kind==='maps'?s.maps.reduce((a,x)=>a+x.stages.length,0):s.stages.length);content.innerHTML=html}
function stageRows(arr){return `<div class="stage-order-list">${arr.map(x=>`<button type="button" class="stage-row" data-stage-entry="${esc(x.entry_id)}"><span class="order">${String(x.play_order||'').padStart(2,'0')}</span><div><b>${esc(x.name_ko)}</b><small>${esc(x.breadcrumb)}</small></div></button>`).join('')}</div>`}
function renderChapter(seriesId,chId){const s=getSeries(seriesId),ch=s?.chapters?.find(x=>x.id===chId);if(!ch)return renderSeries(seriesId);state.stageCtx={type:'chapter',series:seriesId,id:chId};setTitle(`${s.name_ko} ${ch.name_ko}`,'실제 플레이 순서');countText(ch.stages.length);content.innerHTML=`<button class="inline-back" data-stage-series="${esc(seriesId)}" type="button">← ${esc(s.name_ko)}</button>${stageRows(ch.stages)}`}
function renderMap(seriesId,mapId){const s=getSeries(seriesId),m=s?.maps?.find(x=>x.id===mapId);if(!m)return renderSeries(seriesId);state.stageCtx={type:'map',series:seriesId,id:mapId};setTitle(m.name_ko,s.name_ko);countText(m.stages.length);content.innerHTML=`<button class="inline-back" data-stage-series="${esc(seriesId)}" type="button">← ${esc(s.name_ko)}</button>${stageRows(m.stages)}`}
function renderStage(){if(state.query.trim())return stageSearch();if(!state.stageCtx)return renderStageRoot();if(state.stageCtx.type==='series')return renderSeries(state.stageCtx.series);if(state.stageCtx.type==='chapter')return renderChapter(state.stageCtx.series,state.stageCtx.id);if(state.stageCtx.type==='map')return renderMap(state.stageCtx.series,state.stageCtx.id);renderStageRoot()}
function specialMenuCard(x){return `<button class="special-menu-card" type="button" data-special="${esc(x.id)}"><b>${esc(x.name_ko)}</b><small>${x.id==='items'?'전투 아이템·티켓·재화':x.id==='gacha'?'확인된 뽑기 시리즈와 포함 캐릭터':x.id==='combos'?'필요 캐릭터와 발동 효과':x.id==='materials'?'개다래·수석 등 강화 재료':'게임 능력/특성 정보'}</small></button>`}
function renderSpecialRoot(){setTitle('특수','아이템·뽑기·냥콤보 등 게임 정보');countText(state.special.menu.length);content.innerHTML=`<div class="special-menu-grid">${state.special.menu.map(specialMenuCard).join('')}</div>`}
function itemRows(items){return `<div class="simple-list">${items.map(x=>`<button class="simple-row" data-special-item="${x.item_id}"><b>${esc(x.name_ko)}</b><small>${esc(x.category)}${x.description_ko?' · '+esc(x.description_ko.slice(0,80)):''}</small></button>`).join('')}</div>`}
function renderSpecialCategory(id){state.specialCtx=id;let html=`<button class="inline-back" data-special-back="1">← 특수</button>`,total=0;if(id==='items'||id==='materials'){let rows=state.special.items||[];if(id==='materials')rows=rows.filter(x=>x.category==='진화/강화 재료');const q=state.query.trim().toLowerCase();if(q)rows=rows.filter(x=>(x.name_ko+' '+x.description_ko).toLowerCase().includes(q));total=rows.length;setTitle(id==='materials'?'진화 재료':'아이템 / 재화',id==='items'?'전투 아이템·티켓·재화·강화 재료':'개다래·수석 등');html+=itemRows(rows.slice(0,LIMIT))}else if(id==='combos'){let rows=state.special.combos||[],q=state.query.trim().toLowerCase();if(q)rows=rows.filter(x=>(x.name_ko+' '+x.effect_ko+' '+x.required_units.map(u=>u.name_ko).join(' ')).toLowerCase().includes(q));total=rows.length;setTitle('냥콤보','필요 캐릭터와 발동 효과');html+=`<div class="simple-list">${rows.slice(0,LIMIT).map(x=>`<button class="simple-row" data-special-combo="${x.combo_id}"><b>${esc(x.name_ko)}</b><small>${esc(x.effect_ko)} · ${esc(x.required_units.map(u=>u.name_ko).join(' + '))}</small></button>`).join('')}</div>`}else if(id==='gacha'){let rows=state.special.gacha_series||[],q=state.query.trim().toLowerCase();if(q)rows=rows.filter(x=>(x.name_ko+' '+x.members.map(u=>u.name_ko).join(' ')).toLowerCase().includes(q));total=rows.length;setTitle('뽑기','확인된 시리즈와 포함 캐릭터');html+=`<div class="simple-list">${rows.slice(0,LIMIT).map(x=>`<button class="simple-row" data-special-gacha-series="${x.series_id}"><b>${esc(x.name_ko)}</b><small>확인 캐릭터 ${x.member_count}명</small></button>`).join('')}</div><div class="source-note">${esc(state.special.gacha_note)}</div>`}else if(id==='abilities'){setTitle('능력 / 특성','현재 백과 데이터의 대응 능력 기준');const rules=state.strategy.rules||[],seen=new Map();for(const r of rules)if(r.required_trait_key&&!seen.has(r.required_trait_key))seen.set(r.required_trait_key,r.capability_name_ko);const arr=[...seen.entries()].sort((a,b)=>a[1].localeCompare(b[1],'ko'));total=arr.length;html+=`<div class="ability-grid">${arr.map(([k,n])=>`<div class="ability-card"><b>${esc(n)}</b></div>`).join('')}</div>`}countText(total,Math.min(total,LIMIT));content.innerHTML=html}
function specialSearchAll(){const q=state.query.trim().toLowerCase(),hits=[];for(const x of state.special.items||[])if((x.name_ko+' '+x.description_ko).toLowerCase().includes(q))hits.push({kind:'item',id:x.item_id,name:x.name_ko,sub:'아이템 / 재화'});for(const x of state.special.combos||[])if((x.name_ko+' '+x.effect_ko).toLowerCase().includes(q))hits.push({kind:'combo',id:x.combo_id,name:x.name_ko,sub:'냥콤보 · '+x.effect_ko});for(const x of state.special.gacha_series||[])if((x.name_ko+' '+x.members.map(u=>u.name_ko).join(' ')).toLowerCase().includes(q))hits.push({kind:'gacha-series',id:x.series_id,name:x.name_ko,sub:`뽑기 · 확인 캐릭터 ${x.member_count}명`});setTitle('특수 검색',`“${state.query}”`);countText(hits.length,Math.min(hits.length,LIMIT));content.innerHTML=`<div class="simple-list">${hits.slice(0,LIMIT).map(x=>`<button class="simple-row" data-special-${x.kind}="${x.id}"><b>${esc(x.name)}</b><small>${esc(x.sub)}</small></button>`).join('')}</div>`}
function renderSpecial(){if(state.query.trim()&&!state.specialCtx)return specialSearchAll();if(!state.specialCtx)return renderSpecialRoot();renderSpecialCategory(state.specialCtx)}
function renderCurrent(){catalog.hidden=false;detail.hidden=true;if(state.mode==='cat_form'||state.mode==='enemy')renderStandardList();else if(state.mode==='stage')renderStage();else renderSpecial();}
function standardSections(e){return (e.sections||[]).map(g=>{const sm=spans(g.fields||[]);return `<section class="info-group"><h2 class="info-group-title">${esc(g.title)}</h2><div class="info-grid">${(g.fields||[]).map((f,i)=>{const sp=sm[i]||6,links=(f.links||[]).map(l=>`<button class="info-link" type="button" data-open="${esc(l.entry_id)}">${esc(l.label)}</button>`).join('');return `<div class="info-cell span-${sp}"><div class="info-label">${esc(f.label)}</div><div class="info-value">${esc(f.value)}${links?`<div class="info-links">${links}</div>`:''}</div></div>`}).join('')}</div></section>`}).join('')}
function catGachaHtml(e){if(e.category!=='cat_form')return'';const uid=String(e.classification.unit_id),all=state.special.unit_gacha_index?.[uid]||[],named=[];for(const x of all){if(x.name_status!=='KOREAN_SERIES_LABEL_CROSSCHECKED')continue;if(!named.some(y=>y.series_id===x.series_id))named.push(x)}if(!named.length)return'';return `<section class="info-group"><h2 class="info-group-title">포함 뽑기</h2><div class="info-cell span-6"><div class="info-label">확인된 시리즈</div><div class="info-value"><div class="info-links">${named.map(x=>`<button class="info-link" data-special-gacha-series="${x.series_id}">${esc(x.name_ko)}</button>`).join('')}</div></div></div></section>`}
function rosterControl(e){if(e.category!=='cat_form')return'';const u=e.classification.unit_id,f=e.classification.form_no,owned=Roster.isOwned(u,f);return `<div class="hero-actions"><button class="roster-btn ${owned?'owned':''}" type="button" data-roster-unit="${u}" data-roster-form="${f}">${owned?'보유 등록됨 · 해제':'이 형태까지 보유 등록'}</button></div>`}
function nodeFor(e){return stageNodeMap.get(e.entry_id)||null}
function deckPanel(e){if(e.category!=='stage')return'';const node=nodeFor(e),sid=e.classification.stage_native_id||node?.battle_stage_native_id,series=node?.series_id||e.classification.series_code,ch=node?.chapter_no||e.classification.chapter_no;let owned=null,allowed=null,note='',mode=state.deckMode;if(mode==='owned')owned=Roster.read();if(mode==='progress'){const key=series==='EOC'&&ch?`EOC:CH${ch}`:null,pol=key?state.progression.policies?.[key]:null;if(pol){allowed=pol.allowed_entry_ids;note=pol.note}else{mode='all';note=state.progression.fallback.note}}
 const d=Deck.recommend(sid,{owned,allowedEntries:allowed});const cards=d.slots.map(x=>`<button class="deck-card" type="button" data-open="${esc(x.entry_id)}">${imageBox(x.entry_id,x.name_ko,'deck-thumb')}<div class="deck-slot">#${x.slot} · ${esc(x.role_ko)}</div><b>${esc(x.name_ko)}</b><small>비용 ${esc(x.stats.cost)} · 사거리 ${esc(x.stats.range)}</small><p>${esc(x.reasons.slice(0,2).join(' / '))}</p></button>`).join('');const shortage=d.slots.length<10?`<div class="deck-warning">현재 선택 기준에서는 추천 가능한 서로 다른 캐릭터가 ${d.slots.length}종입니다. 없는 강캐를 억지로 채우지 않습니다.</div>`:'';return `<section class="deck-panel"><div class="deck-head"><div><h2>추천 편성</h2><p>공식 공략 공식이 아닌 KR15.5 데이터 기반 추천입니다.</p></div><div class="deck-mode"><button data-deck-mode="progress" class="${state.deckMode==='progress'?'active':''}">진행 기준</button><button data-deck-mode="owned" class="${state.deckMode==='owned'?'active':''}">보유만 (${Roster.count()})</button><button data-deck-mode="all" class="${state.deckMode==='all'?'active':''}">전체 참고</button></div></div>${note?`<div class="deck-note">${esc(note)}</div>`:''}${shortage}<div class="deck-grid">${cards}</div></section>`}
function detailHtml(e){const node=nodeFor(e),crumb=node?.breadcrumb||e.classification?.hierarchy_breadcrumb||'',displayName=node?.name_ko||e.names.ko;const hero=`${crumb?`<div class="breadcrumb">${esc(crumb)}</div>`:''}<div class="detail-hero"><div class="hero-image">${e.category==='stage'?'':imageBox(e.entry_id,displayName,'hero-img')}</div><div class="hero-copy"><h1>${esc(displayName)}</h1>${e.names.ja?`<div class="ja">${esc(e.names.ja)}</div>`:''}<div class="type">${esc(e.ui_category)}</div>${rosterControl(e)}</div></div>`;const rel=(e.relations||[]).length?`<div class="relation-row">${e.relations.map(r=>`<button data-open="${esc(r.entry_id)}">${esc(r.label)}</button>`).join('')}</div>`:'';return `<button class="detail-back" type="button" data-detail-back="1">← 이전</button>`+hero+`<div class="detail-sections">${standardSections(e)}${catGachaHtml(e)}</div>`+deckPanel(e)+rel}
function catFromId(id){if(id.startsWith('cat:'))return'cat_form';if(id.startsWith('enemy:'))return'enemy';return'stage'}
async function getEntry(id,cat){if(storyDetailMap.has(id))return storyDetailMap.get(id);const map=await loadCategory(cat);return map.get(id)||null}
async function openEntry(id,cat,push=true){const e=await getEntry(id,cat);if(!e)return;if(push&&state.current)state.history.push(state.current);state.current={id,cat};catalog.hidden=true;detail.hidden=false;detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail);window.scrollTo({top:0,behavior:'auto'})}
function bindDetail(e){detail.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openEntry(b.dataset.open,catFromId(b.dataset.open))));const rb=detail.querySelector('[data-roster-unit]');if(rb)rb.addEventListener('click',()=>{const u=+rb.dataset.rosterUnit,f=+rb.dataset.rosterForm;if(Roster.isOwned(u,f))Roster.remove(u);else Roster.setOwned(u,f);detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail)});detail.querySelectorAll('[data-deck-mode]').forEach(b=>b.addEventListener('click',()=>{state.deckMode=b.dataset.deckMode;detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail)}));const back=detail.querySelector('[data-detail-back]');if(back)back.addEventListener('click',goBack);detail.querySelectorAll('[data-special-gacha-series]').forEach(b=>b.addEventListener('click',()=>openSpecialGachaSeries(+b.dataset.specialGachaSeries)))}
function goBack(){if(state.history.length){const p=state.history.pop();openEntry(p.id,p.cat,false)}else{state.current=null;detail.hidden=true;catalog.hidden=false;renderCurrent()}}
function openSpecialItem(id){const x=(state.special.items||[]).find(x=>x.item_id===id);if(!x)return;state.current={special:'item',id};catalog.hidden=true;detail.hidden=false;detail.innerHTML=`<button class="detail-back" data-detail-special-back>← 이전</button><div class="special-detail"><h1>${esc(x.name_ko)}</h1><div class="tag">${esc(x.category)}</div><p>${esc(x.description_ko||'클라이언트 설명 없음')}</p><small>아이템 ID ${x.item_id} · KR 15.5.0</small></div>`;detail.querySelector('[data-detail-special-back]').onclick=()=>{detail.hidden=true;catalog.hidden=false;renderCurrent()}}
function openSpecialCombo(id){const x=(state.special.combos||[]).find(x=>x.combo_id===id);if(!x)return;catalog.hidden=true;detail.hidden=false;detail.innerHTML=`<button class="detail-back" data-detail-special-back>← 이전</button><div class="special-detail"><h1>${esc(x.name_ko)}</h1><h2>${esc(x.effect_ko)}</h2><div class="member-grid">${x.required_units.map(u=>`<button data-open="${esc(u.entry_id)}">${imageBox(u.entry_id,u.name_ko,'member-thumb')}<b>${esc(u.name_ko)}</b></button>`).join('')}</div></div>`;detail.querySelector('[data-detail-special-back]').onclick=()=>{detail.hidden=true;catalog.hidden=false;renderCurrent()};detail.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEntry(b.dataset.open,'cat_form'));bindImageFallback(detail)}
function openSpecialGachaSeries(id){const x=(state.special.gacha_series||[]).find(x=>x.series_id===id);if(!x)return;state.mode='special';activeNav();catalog.hidden=true;detail.hidden=false;detail.innerHTML=`<button class="detail-back" data-detail-special-back>← 이전</button><div class="special-detail"><h1>${esc(x.name_ko)}</h1><p>${esc(x.note||'KR 15.5.0 클라이언트 구성 기준')}</p><div class="member-grid">${x.members.map(u=>`<button data-open="${esc(u.entry_id)}">${imageBox(u.entry_id,u.name_ko,'member-thumb')}<b>${esc(u.name_ko)}</b></button>`).join('')}</div><small>확인 캐릭터 ${x.member_count}명</small></div>`;detail.querySelector('[data-detail-special-back]').onclick=()=>{detail.hidden=true;catalog.hidden=false;renderSpecialCategory('gacha')};detail.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEntry(b.dataset.open,'cat_form'));bindImageFallback(detail)}
content.addEventListener('click',e=>{let b=e.target.closest('[data-entry]');if(b)return openEntry(b.dataset.entry,b.dataset.category);b=e.target.closest('[data-stage-entry]');if(b)return openEntry(b.dataset.stageEntry,'stage');b=e.target.closest('[data-stage-series]');if(b)return renderSeries(b.dataset.stageSeries);b=e.target.closest('[data-stage-chapter]');if(b)return renderChapter(b.dataset.series,b.dataset.stageChapter);b=e.target.closest('[data-stage-map]');if(b)return renderMap(b.dataset.series,b.dataset.stageMap);b=e.target.closest('[data-stage-back]');if(b){state.stageCtx=null;return renderStageRoot()}b=e.target.closest('[data-special]');if(b)return renderSpecialCategory(b.dataset.special);b=e.target.closest('[data-special-back]');if(b){state.specialCtx=null;return renderSpecialRoot()}b=e.target.closest('[data-special-item]');if(b)return openSpecialItem(+b.dataset.specialItem);b=e.target.closest('[data-special-combo]');if(b)return openSpecialCombo(+b.dataset.specialCombo);b=e.target.closest('[data-special-gacha-series]');if(b)return openSpecialGachaSeries(+b.dataset.specialGachaSeries)});
search.addEventListener('input',e=>{state.query=e.target.value;if(state.current){state.current=null;detail.hidden=true;catalog.hidden=false}renderCurrent()});
document.querySelectorAll('.bottom-toolbar [data-mode]').forEach(b=>b.addEventListener('click',()=>showMode(b.dataset.mode)));
const home=document.querySelector('[data-action="home"]');if(home)home.addEventListener('click',()=>showMode('cat_form'));
window.addEventListener('swbattlecats:roster-changed',()=>{if(state.current?.cat==='stage'){getEntry(state.current.id,'stage').then(e=>{detail.innerHTML=detailHtml(e);bindDetail(e);bindImageFallback(detail)})}});
boot().catch(err=>{content.innerHTML='<div class="empty">데이터를 불러오지 못했습니다.<br>배포 파일 구성을 확인해 주세요.</div>';console.error(err)});
window.SWBattleCatsEncyclopediaV036={showMode,openEntry};
})();
